# Site settings
title: love life ,love code
author: jiangtaibao
author_avatar: /images/14925803.png
email: 18723126233@163.com
description: 热爱生活，热爱代码 
url: "https://jtbadbb.github.io/"
domain: "https://jtbadbb.github.io/"
github_username: jtbadbb
github_site_repo: jtbadbb/jtbadbb.github.io
disqus: monsterslayer


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


gems:
  - jekyll-sitemap
